services:
  yolo-api:
    image: ${IMAGE:-ghcr.io/manuela-menezes/yolo-edge-api/yolo-api:latest}
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: yolo-api

    ports:
      - "8000:8000"

    privileged: true

    volumes:
      - ./models:/app/models:ro
      - ./output:/app/output
      - ./images:/app/images:ro
      - /dev:/dev
      - /run/udev:/run/udev:ro

    environment:
      - MODEL_NAME=yolo-epi.pt

    networks:
      - yolo-net

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  yolo-client:
    build:
      context: .
      dockerfile: Dockerfile.client

    container_name: yolo-client

    volumes:
      - ./images:/client/images:ro
      - ./output:/client/output

    environment:
      - API_URL=http://yolo-api:8000

    networks:
      - yolo-net

    depends_on:
      yolo-api:
        condition: service_healthy

  yolo-stream:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-stream
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - ./stream:/app/stream
      - ./models:/app/models:ro
      - ./preprocessing:/app/preprocessing
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - MODEL_NAME=yolov8n.pt
    command: >
      python3 stream/mjpeg_server.py
      --device 0
      --model models/yolo-epi.pt
      --infer-every 3
      --infer-size 320
      --port 5000
    restart: unless-stopped
    depends_on:
      - yolo-api

networks:
  yolo-net:
    driver: bridge

